In [1]:
import glob
import pandas as pd

In [8]:
path = r'' # use your path
all_files = glob.glob("*.csv")

li = []

print("There are "+str(len(all_files))+" files")
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

allstations = pd.concat(li, axis=0, ignore_index=True)

There are 39 files

In [12]:
allstations.drop(columns=["Unnamed: 0"]).to_csv("./New/AQI_Data_27Jan2021.csv",encoding="utf-8")

In [13]:
allstations

,Unnamed: 0,State,City,Station_ID,Station_Name,Date,PM2.5_average,PM2.5_minimum,PM2.5_maximum,PM10_average,...,SO2_maximum,CO_average,CO_minimum,CO_maximum,OZONE_average,OZONE_minimum,OZONE_maximum,NH3_average,NH3_minimum,NH3_maximum
0,0,Gujarat,Ahmedabad,site_308,"Maninagar, Ahmedabad - GPCB",31/12/2020,134.0,46.0,270.0,120.0,...,57.0,62.0,17.0,110.0,30.0,1.0,124.0,NaN,NaN,NaN
1,1,Gujarat,Ahmedabad,site_308,"Maninagar, Ahmedabad - GPCB",30/12/2020,111.0,37.0,259.0,127.0,...,46.0,49.0,8.0,105.0,26.0,1.0,98.0,NaN,NaN,NaN
2,2,Gujarat,Ahmedabad,site_308,"Maninagar, Ahmedabad - GPCB",29/12/2020,97.0,52.0,246.0,175.0,...,44.0,65.0,8.0,116.0,28.0,1.0,101.0,NaN,NaN,NaN
3,3,Gujarat,Ahmedabad,site_308,"Maninagar, Ahmedabad - GPCB",28/12/2020,108.0,45.0,308.0,121.0,...,29.0,39.0,8.0,107.0,33.0,2.0,162.0,NaN,NaN,NaN
4,4,Gujarat,Ahmedabad,site_308,"Maninagar, Ahmedabad - GPCB",27/12/2020,141.0,62.0,322.0,136.0,...,56.0,116.0,8.0,179.0,46.0,1.0,189.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,4779,Delhi,Delhi,site_5395,"Lodhi Road, Delhi - IITM",05/07/2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7172,4780,Delhi,Delhi,site_5395,"Lodhi Road, Delhi - IITM",04/07/2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7173,4781,Delhi,Delhi,site_5395,"Lodhi Road, Delhi - IITM",03/07/2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7174,4782,Delhi,Delhi,site_5395,"Lodhi Road, Delhi - IITM",02/07/2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7175,4783,Delhi,Delhi,site_5395,"Lodhi Road, Delhi - IITM",01/07/2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN